name: example
on:
  push:
    branches:
    - main

env:
  SSH_KEYPAIR: ${{ secrets.SSH_KEYPAIR }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    # Add support for more platforms with QEMU (optional)
    # https://github.com/docker/setup-qemu-action
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
          # registry: <aws-account-number>.dkr.ecr.<region>.amazonaws.com
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
    - name: Build and push
      uses: docker/build-push-action@v5
      with:
        push: true
        tags: wjma90/myapp:latest

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Set permissions for private key
      run: |
        echo "${{ env.SSH_KEYPAIR }}" > key.pem
        chmod 600 key.pem
    - name: Clean Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@18.208.163.210 'docker rmi -f wjma90/myapp:latest || true'
    - name: Pull Docker image
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@18.208.163.210 'docker pull wjma90/myapp:latest'
    - name: Stop running container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@18.208.163.210 'sudo docker rm -f $(docker ps -aq) || true'
    - name: Run new container
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ubuntu@18.208.163.210 'sudo docker run -d -p 80:80 wjma90/myapp'
    